other:
  characters_per_line: 85
paths:
  mcrun_path: /usr/mcstas/3.3//bin/
  mcstas_path: /usr/mcstas/3.3/
  mcxtrace_path: /Applications/McXtrace-1.5.app/Contents/Resources/mcxtrace/1.5/
  mxrun_path: /Applications/McXtrace-1.5.app/Contents/Resources/mcxtrace/1.5/bin/
